name: Code Coverage

on:
    push:
        branches:
            - master

jobs:
    steps:
        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # needed for tests
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: pcov

            -   run: composer install --no-progress --ansi

            -
                name: Code Coverage
                run: |
                    vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                    # coveralls.io
                    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                    php php-coveralls.phar --verbose
                env:
                    COVERALLS_REPO_TOKEN: 'nEEi7ayyJ4Ly6ZOuE4EdKS9uNue5JZCNL'
