# see https://sonarcloud.io/dashboard?id=symplify_symplify
name: Sonar

on:
    push:
        branches:
            - master

jobs:
    sonar:
        name: Sonar
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # needed for tests
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer install --no-progress --ansi

            # generate sonar file configuration
            -   run: composer sonar --ansi

            -
                name: Sonar Cube
                uses: sonarsource/sonarcloud-github-action@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    # get token here: https://sonarcloud.io/account/security/
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
